apiVersion: v1

kind: ConfigMap

metadata:
  name: config

data:
  db_url: "postgresdb"
  db_port: "5432"
  db_name: "app"
  db_user: "postgres"
  DATABASE_URL: "postgresql://postgres:postgres@postgresdb:5432/app"

